### ISSUE TITLE
Take down nixos.wiki or set up URL redirect

### ISSUE THREAD

**Issue by cvoges12** [NixOS/nixos-wiki-infra#124]
I think that it is known at this point that NixOS now has an official wiki. But the old wiki (<https://nixos.wiki>) should be removed or have  the domain redirect to <https://wiki.nixos.org>.

**Comment by Lassulus** [comment]
This is not possible, since the admin of the old wiki doesn't want to do that.

**Comment by Mic92** [comment]
Yeah. We tried everything https://github.com/NixOS/foundation/issues/113

**Comment by cvoges12** [comment]
:(
