### ISSUE TITLE
Consider offering public XML dumps

### ISSUE THREAD

**Issue by emilazy** [NixOS/nixos-wiki-infra#132]
MediaWiki supports an XML dump format that is suitable for external processing and can be imported into another MediaWiki instance. Wikipedia and other wikis publish these regularly. I think automatically creating and publishing these would be a good way to let people get at the wiki content and avoid lock‐in.

**Comment by Mic92** [comment]
We already do this. Check the readme

**Comment by emilazy** [comment]
Ah, I’m sorry; I tried to find it on the wiki itself and couldn’t, though I might just have been looking in the wrong place. Didn’t think to check the infra repository for pointers to things like that (admittedly no excuse when I thought to report an issue here!).

**Comment by Mic92** [comment]
No worries. Have fun forking it.
