### ISSUE TITLE
Would it be appropriate to link to my package search CLI?

### ISSUE THREAD

**Issue by peterldowns** [NixOS/nixos-wiki-infra#157]
👋 I'm the author of [peterldowns/nix-search-cli](https://github.com/peterldowns/nix-search-cli), a CLI frontend for the search.nixos.org elasticsearch index. I believe this tool is useful and it's begun to get some wider adoption in the community, although it's still relatively unknown. It [has been added to nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/ni/nix-search-cli/package.nix). I believe it is the most beginner/newbie/general-user friendly method of searching for the appropriate nixpkgs attr to install in order to use a specific program.

I was wondering if it would be appropriate / possible to add a reference to it on the [Searching packages wiki page](https://wiki.nixos.org/wiki/Searching_packages). I would like to add it to the "Reverse search" section of that page.

Would this change be welcome?

**Comment by Mic92** [comment]
Sounds good.

**Comment by peterldowns** [comment]
@Mic92 OK, I created an account and updated that page.
