### ISSUE TITLE
Switching theme breaks layout

### ISSUE THREAD

**Issue by mrmagic223325** [NixOS/nixos-wiki-infra#38]
Switching from dark mode to light mode and vice versa breaks the layout until the page is refreshed

![image](https://github.com/NixOS/nixos-wiki-infra/assets/76184901/428d4b0a-fddc-4c36-924b-428d946572ff)

**Comment by Mic92** [comment]
Could you report this issue upstream? We are just using this extension here: https://www.mediawiki.org/wiki/Extension:DarkMode

**Comment by Mic92** [comment]
This is the extension: https://github.com/wikimedia/mediawiki-extensions-DarkMode

**Comment by mrmagic223325** [comment]
> Could you report this issue upstream? We are just using this extension here: https://www.mediawiki.org/wiki/Extension:DarkMode

No, I don't want to create a MediaWiki account as the GitHub repository is just a read-only mirror.
:3

**Comment by Mic92** [comment]
Ok. Than it will stay broken for longer...

**Comment by Mic92** [comment]
I could also confirm we have this file in our mediawiki version: https://github.com/wikimedia/mediawiki/blob/master/resources/lib/ooui/themes/wikimediaui/images/icons/moon.svg

**Comment by mrmagic223325** [comment]
Closing as this seems to have been fixed.
