### ISSUE TITLE
The flake article

### ISSUE THREAD

**Issue by deviantsemicolon** [NixOS/nixos-wiki-infra#46]
As per the NixOS wiki contribution guidelines, language on the wiki has to be simple and concise. As of writing this, the flake article is the exact opposite of that. I'm not the most knowledgeable on flakes, but if anyone here is, I think this is an important thing to do given how widely used flakes are.

**Comment by RaitoBezarius** [comment]
That's not the place for such discussions, please use the Discussion page of that article and work with content editors to get the desired result.
