### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by linyinfeng** [NixOS/nixos-wiki-infra#48]
A multilingual wiki can make NixOS more international, but it may also require more complex maintenance and moderation. So I'm not sure whether it is a good idea to make the site multilingual, it is just a suggestion.

I'm not familiar with MediaWiki. After some search, it seems that the recommended way to setup a multilingual MediaWiki is to use [MediaWiki Language Extension Bundle](https://www.mediawiki.org/wiki/MediaWiki_Language_Extension_Bundle).
<https://stackoverflow.com/questions/12144303/how-to-make-a-mediawiki-site-multilingual>

> The MediaWiki language extension bundle (MLEB) is a curated set of MediaWiki extensions offering multilingual features. It attempts to provide an easy way to bring comprehensive language support to a MediaWiki.

> The current version of MLEB contains the following extensions: [[1]](https://www.mediawiki.org/wiki/MediaWiki_Language_Extension_Bundle#cite_note-locUpd-1)
> 
> * [Babel](https://www.mediawiki.org/wiki/Special:MyLanguage/Extension:Babel)
> * [CLDR](https://www.mediawiki.org/wiki/Special:MyLanguage/Extension:CLDR) ("Common Locale Data Repository")
> * [CleanChanges](https://www.mediawiki.org/wiki/Special:MyLanguage/Extension:CleanChanges)
> * [Translate](https://www.mediawiki.org/wiki/Special:MyLanguage/Extension:Translate)
> * [UniversalLanguageSelector](https://www.mediawiki.org/wiki/Special:MyLanguage/Extension:UniversalLanguageSelector)
> 
> MLEB has a quarterly release schedule, so that you can easily stay on the cutting edge with the constantly improving language support. The bundle is tested against recent MediaWiki release versions, so you can avoid most of the temporary breaks that would happen if you were using the latest development versions of each extension.

**Comment by Mic92** [comment]
I know that archlinux just has distinguished installations of mediawiki: https://wiki.archlinux.de/title/Hauptseite
But I don't know if they did this for historical reasons.

**Comment by Mic92** [comment]
Do you know any wiki that uses these extensions?

**Comment by Lassulus** [comment]
I would be interested into multi-language support. As a requirement for enabling a certain language we would need to have a speaker of that language in the moderation team. Otherwise it's a bit hard to moderate :)

**Comment by linyinfeng** [comment]
> I know that archlinux just has distinguished installations of mediawiki: https://wiki.archlinux.de/title/Hauptseite But I don't know if they did this for historical reasons.

Here are the talks about i18n on arch wiki <https://wiki.archlinux.org/title/Help_talk:I18n>.
Currently, Arch Wiki is using a mixed method: <https://wiki.archlinux.org/title/Help:I18n#Languages>.
* In the main site, it use language name suffixes in page titles to distinguish pages for different languages.
* For several languages, it uses interwiki links to external sites.

tarakbumba proposed to use [Extension:Translate](https://www.mediawiki.org/wiki/Extension:Translate) in Arch Wiki at 2011.
<https://bbs.archlinux.org/viewtopic.php?id=128610>
<https://bugs.archlinux.org/task/26638>
But, the community decided not to use the extension.

It seems that the relevant discussion records in the Arch community are lost, I can not find many discussions about why they made the decision.
Here I quote [Lahwaacz](https://wiki.archlinux.org/title/User:Lahwaacz)'s comment in the talk.
> I'm pretty sure we already discussed [mw:Extension:Translate](https://www.mediawiki.org/wiki/Extension:Translate), but I can't find the discussion now. We're not fans of [what the extension does to the original page](https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Extension:Translate/Page_translation_example#Step_4:_Making_changes), the markers get messy pretty quickly and they require every editor, not just translators, to be aware of the translation workflow and to deal with the markers correctly. The other extensions from the language bundle don't help with translating content, they just improve the user interface.
<https://wiki.archlinux.org/title/Help_talk:I18n#c-Lahwaacz-2021-04-30T06:59:00.000Z-PyanayaLuna-2021-04-30T01:53:00.000Z>

The comment points out some disadvantages of the extension, maybe this is why the Arch community sticks to their method.

> Do you know any wiki that uses these extensions?

The main extension is [Extension:Translate](https://www.mediawiki.org/wiki/Extension:Translate), [here](https://www.mediawiki.org/wiki/Extension:Translate#Prominent_users_of_the_Translate_extension) and [here](https://en.wikipedia.org/wiki/Translatewiki.net#Notable_uses) lists some prominent users of the extension.
The other extensions in the bundle are maily used to improve the user interface.

I see two linux wikis in the list:

* The **Gentoo** wiki, for example, their handbook page is multilingual, supported by this extension, <https://wiki.gentoo.org/wiki/Handbook:Main_Page>.
* The **KDE** UserBase wiki, <https://userbase.kde.org/Welcome_to_KDE_UserBase>.

**Comment by mrmagic223325** [comment]
> I would be interested into multi-language support. As a requirement for enabling a certain language we would need to have a speaker of that language in the moderation team. Otherwise it's a bit hard to moderate :)

I think the way it is done on the Gentoo wiki is quite good:

- Becoming a translator requires the user to submit a request to a [wiki page](https://wiki.gentoo.org/wiki/Gentoo_Wiki:Translator_account_requests)
- If this user is the first translator for their language they must also translate [this](https://wiki.gentoo.org/wiki/Help:Translating) wiki page (requirements can be different for this wiki)

Having a speaker of the language on the moderation team would obviously be a good thing, but first time translations could also be proofread by other speakers of the language. Personally I'd be really interested in translating articles into German as I'm a head translator of the Gentoo Wiki.

**Comment by Mic92** [comment]
We discussed this in the NixOS wiki meeting today. And we want to have multi-language in the near future but want a little bit time to evaluate how we can technical ways of implemented that. Also to settle the dust of the recent restructuring a bit.

**Comment by Mic92** [comment]
After fixing a regression in the [nix package manager](https://github.com/NixOS/nix/pull/11051) and working around a limitation an interesting limitation that postgresql regarding column indexes: https://github.com/NixOS/nixos-wiki-infra/pull/117

we finally have the mediawiki translation extension working: https://www.mediawiki.org/wiki/Extension:Translate

Since the mediawiki translate extension takes a bit to get used to, I recommend watching this 2-video tutorial: https://www.mediawiki.org/wiki/Help:Extension:Translate/Page_translation_example
