### ISSUE TITLE
Infobox table problems

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-wiki-infra#55]
<details><summary>Screenshots</summary>

![image](https://github.com/NixOS/nixos-wiki-infra/assets/132835/e754c2d1-1fa7-4d0e-ab59-817adce504be)

![image](https://github.com/NixOS/nixos-wiki-infra/assets/132835/1ab6a3b2-913f-41a3-a37e-ac692ed68efe)

</details>

1. Font is too big
2. (might be linked to 1) goes over the width of the page (highlighted in red in the second screenshot)

Blocked on #56

**Comment by samueldr** [comment]
Verified to be part of Common.css edits (which relied on the Tweeki theme semantics)

![image](https://github.com/NixOS/nixos-wiki-infra/assets/132835/8b1b1dd9-0b0d-4618-b9f3-b9d5a412b76e)

**Comment by samueldr** [comment]
*Fixed*

 - https://wiki.nixos.org/w/index.php?title=MediaWiki%3ACommon.css&diff=11521&oldid=4616
 - https://wiki.nixos.org/wiki/User:0x4A6F
 - https://wiki.nixos.org/wiki/NixOS_on_ARM/Raspberry_Pi_3

Might require some hard refreshing depending on how things get cached. Though it worked without a hard refresh on my end.

The whole CSS needs to be reviewed anyways, in tandem with selecting a theme (if desired). This is why this was only commented out for now.

**Comment by RaitoBezarius** [comment]
What a beast <3.
