### ISSUE TITLE
Some suggestions for improvements

### ISSUE THREAD

**Issue by sdht0** [NixOS/nixos-wiki-infra#60]
- [ ] There does not seem to be a way to setup email notifications yet?
- [x] The "external link" css icon is also appearing for internal talk page links, such as here: https://wiki.nixos.org/wiki/Template:Expansion#Example
- [ ] Mention the content license in the footer.

Helpful extensions:
- [ ] https://www.mediawiki.org/wiki/Extension:DiscussionTools so that talk pages have reply buttons
- [ ] https://www.mediawiki.org/wiki/Notifications
- [ ]  https://www.mediawiki.org/wiki/Extension:Thanks

**Comment by Mic92** [comment]
@samueldr do these CSS changes sound good to you?

**Comment by Mic92** [comment]
We have an email server configured in mediawiki, who do we need to do for email notifications do beyond that?

**Comment by Mic92** [comment]
Extension:DiscussionTools sounds ok, given it's developed by mediawiki.

**Comment by sdht0** [comment]
> We have an email server configured in mediawiki, who do we need to do for email notifications do beyond that?

These need to be enabled I think:
https://www.mediawiki.org/wiki/Manual:$wgEnotifUserTalk
https://www.mediawiki.org/wiki/Manual:$wgEnotifWatchlist

This will be nice too:
https://www.mediawiki.org/wiki/Notifications

**Comment by samueldr** [comment]
> @samueldr do these CSS changes sound good to you?

Which CSS changes? Or do you mean the request for changes?

**Comment by sdht0** [comment]
Nice, thanks @Mic92!
