### ISSUE TITLE
Multilanguage support on the Wiki

### ISSUE THREAD

**Issue by ratsclub** [NixOS/nixos-wiki-infra#64]
Someone brought up on the Brazilian NixOS community that there isn't much Nix-related content in Brazilian Portuguese (PT-BR). I wonder if the community could start working on this by translating/contributing to the wiki in Brazilian Portuguese.

This could also open space for other languages!

**Comment by mweinelt** [comment]
Duplicate #48

**Comment by ratsclub** [comment]
Oh, sorry, I didn't see this one!
