### ISSUE TITLE
Search is hidden on mobile

### ISSUE THREAD

**Issue by bibor** [NixOS/nixos-wiki-infra#66]
The following screenshot shows, that the search is normally hidden on mobile. No search bar or button is shown in the default view, or by scrolling down.
![Search Hidden](https://github.com/NixOS/nixos-wiki-infra/assets/1624046/52692b1b-aac6-497a-9a49-d2b47ee8f97c)

The search however becomes visible, if the user scrolls sideways. This is very unintuitive for a mobile use case.

![Search Visible](https://github.com/NixOS/nixos-wiki-infra/assets/1624046/902eb7c6-dd18-4aa2-be43-f433c59d929b)

For better UX, the search bar or a search button should be visible without horizontal scrolling.

**Comment by samueldr** [comment]
Fixed with https://wiki.nixos.org/w/index.php?title=MediaWiki:Vector.css&oldid=12142

Somehow the theme default to a really wide `min-width`, which is pretty much unneeded.

(Search box is iffy, but that will be fixed too.)

**Comment by JulienMalka** [comment]
Thanks you @samueldr !
