### ISSUE TITLE
Nixvim documentation page request

### ISSUE THREAD

**Issue by Eveeifyeve** [NixOS/nixos-wiki-infra#68]
### Comment
Nix vim is a nice to configure vim it is based on NeoVim but the only documentation is [here][docsVim] it allows you to configure vim using nix. So whats so special about?? It special since you don't need to have a separate config for vim in Lua rather you can just use nix. You can use Lua for plugins but It set your vim up for Nix/NixOS. Since the wiki just came out it would be cool to include something that use nix.

### Links to help-out:
- https://nix-community.github.io/nixvim/
- https://github.com/nix-community/nixvim

[docsVim]: https://nix-community.github.io/nixvim/

**Comment by Mic92** [comment]
That would be great. You can create this page by visiting https://wiki.nixos.org/w/index.php?title=Special:UserLogin&returnto=NixOS+Wiki
