### ISSUE TITLE
Really bad SEO

### ISSUE THREAD

**Issue by omentic** [NixOS/nixos-wiki-infra#77]
This site (https://wiki.nixos.org/) has *really* bad SEO in comparison to the old site (https://nixos.wiki/).

The following search: [zfs nixos wiki](https://www.google.com/search?q=zfs+nix+wiki) has *zero* results from wiki.nixos.org. Even changing it to [zfs nixos wiki wiki.nixos.org](https://www.google.com/search?q=zfs+nix+wiki+wiki.nixos.org) does not do much: and the page in question, https://wiki.nixos.org/wiki/ZFS, is nowhere to be seen.

I do not know much about SEO, but this seems possibly due to wiki.nixos.org lacking a robots.txt. It might be prudent to copy https://nixos.wiki/robots.txt directly.

**Comment by Mic92** [comment]
I went through backlink search machines and fixes nixos.wiki links in the most obvious places. https://discourse.nixos.org/t/help-wanted-updating-links-to-point-to-the-new-nixos-wiki/45185
But there is maybe some opportunity to automate this further.

**Comment by omentic** [comment]
Nice, I heard someone had been doing that! But that's been going on for a while, right? Weirdly poor SEO *still* suggests to me that there's something else wrong: the line `Allow: /wiki/Special:AllPages` line in nixos.wiki's robots.txt does seem like it is SEO related.

**Comment by Mic92** [comment]
Now finally deployed. I am open to other SEO tipps.
