### ISSUE TITLE
incorrect example for boot.kernelParams

### ISSUE THREAD

**Issue by deng232** [NixOS/nixos-wiki-infra#89]
according to the https://search.nixos.org/options
boot.kernelParams is type of  ```list of string, with spaces inside double quotes ```

but in https://nixos.wiki/wiki/Linux_kernel, it gave out example 
```
{ pkgs, config, ... }:
{
  boot.kernelParams = [ 
    // example settings
    "quiet"
    "splash"
    usbcore.blinkenlights=1 // example kernel module parameter
  ];
}
```
the line ```usbcore.blinkenlights=1```  which will raise syntax error

**Comment by mweinelt** [comment]
This has been fixed in the [official wiki](https://wiki.nixos.org/wiki/Linux_kernel#Customizing_kernel_module_parameters) a while ago.

Please update your links to use wiki.nixos.org instead.
